[build-system]
requires = ["scikit-build-core", "swig==4.1.1"]
build-backend = "scikit_build_core.build"

[project]
name = "orbits"
version = "0.0.1"

[tool.scikit-build]
build.verbose = true
logging.level = "INFO"
build-dir = "build/{wheel_tag}"
# wheel.install-dir = "orbits"
